version: '3'
services:
  db:
    image: postgres:9.6.12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - .:/calculator
    ports:
      - "3000:3000"
    depends_on:
      - db
