default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password:
development:
  <<: *default
  database: calculator_development

test:
  <<: *default
  database: calculator_test

production:
  <<: *default
  database: calculator_production
  username: calculator
  password: <%= ENV['CALCULATOR_DATABASE_PASSWORD'] %>
